language: ruby
rvm:
  - 2.3.1

bundler_args: "--without development --deployment"

cache: bundler

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rails db:migrate RAILS_ENV=test

script:
  - bundle exec rspec
